package com.vidhan.calculator;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-08-08T22:44:04.945+01:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "CalculatorService",
                  wsdlLocation = "file:Calculator.wsdl",
                  targetNamespace = "http://vidhan.com/Calculator")
public class CalculatorService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://vidhan.com/Calculator", "CalculatorService");
    public static final QName CalculatorPort = new QName("http://vidhan.com/Calculator", "CalculatorPort");
    static {
        URL url = null;
        try {
            url = URI.create("file:Calculator.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculatorService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:Calculator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalculatorPortType
     */
    @WebEndpoint(name = "CalculatorPort")
    public CalculatorPortType getCalculatorPort() {
        return super.getPort(CalculatorPort, CalculatorPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorPortType
     */
    @WebEndpoint(name = "CalculatorPort")
    public CalculatorPortType getCalculatorPort(WebServiceFeature... features) {
        return super.getPort(CalculatorPort, CalculatorPortType.class, features);
    }

}
